# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5931ad5b4993d2d34e5ad8203289848d22aa1e31eee1cfe0c3407ec78541fdade9ab6498013fbacbf896b4dc5a94e87429562a3968c7686e8f2b9971267059f5

test:
  secret_key_base: ed00e83b0e9a942823054714bdd4da995b7a95d914cc39fd40ddda56e499f563f7a1314f250ee186cc90eb2b03dd23f5cb87e3052da8b246363d0335e504ab99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
